# Generated by Django 4.1.4 on 2022-12-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Food'), ('DW', 'Drink'), ('D', 'Desert')], max_length=2),
        ),
    ]
